### ISSUE TITLE
Dependencies are not installed for gem packages

### ISSUE THREAD

**Issue by uzytkownik** [defunkt/rip#51] opened 2009-06-25 15:31 UTC
<pre>% rip install merb 1.0.10 
running install hook for merb
Successfully installed merb (1.0.11)
% rip list
ripenv: merbglobal-ruby18

merb (1.0.11)
</pre>

There is no merb-core & co.

**Comment by mloughran** [comment] 2009-06-26 09:52
This is a duplicate of issue #1

**Comment by defunkt** [comment] 2009-07-14 07:24
Closing dupe

**Closed as completed by defunkt** 2009-07-14 07:24 UTC
